name: Despertador Automatico Streamlit

on:
  schedule:
    # Se ejecuta automáticamente cada 3 horas
    - cron: '0 */3 * * *'
  workflow_dispatch: # Agrega un botón en GitHub para ejecutarlo manualmente si lo deseas

jobs:
  wake-streamlit:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Extendido para soportar los 35+ minutos que dura el script con las pausas
    steps:
      - name: Obtener código del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Playwright y dependencias
        run: |
          pip install playwright
          playwright install chromium

      - name: Ejecutar navegador automatizado
        run: python keep_alive.py